//Define the general variables
var value = [];
//var year_initial = 2011;
//var year_final = 2011;
//var month_initial = 10;
//var month_final = 10;
//var day_initial = 1;
//var day_final = 1;
//var time_delay = 1000;
var frames_per_second = 1;
var map_array = [];
var bounds;
var overlay_obj = new Array();
var point_overlay;
var static_overlay_obj = new Array();
var overlay_mask = new Array();
var overlayImageSelect = [];
var srcImage = [];
var srcColorbar = [];
var markersArray = [];
var m;
var Sidebar_divs = ["DC_div","Forcing_div"];
//var overlay_name = ["DEM","Basins","Area","TI","ROratio","LC"];
srcImage[2] = 'Sample_Images/rp_area.gif';
//srcImage[1] = 'Webpage_scripts/rp_basins.gif';
srcImage[1] = '';
srcImage[0] = 'Sample_Images/rp_dem.gif';
srcImage[3] = 'Sample_Images/rp_ti.gif';
//srcImage[4] = 'Sample_Images/rp_roratio.gif';
srcImage[4] = 'Data/Images/Forcings/Daily/prec/prec_19700110.gif';
srcImage[5] = 'Sample_Images/rp_UMD.gif';